# Generated by Django 5.0.4 on 2024-05-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_hotel_comment_image_imageroom_room_booking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='HotelImage',
        ),
    ]
