# Generated by Django 5.0.4 on 2024-05-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_remove_hotel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.SmallIntegerField(),
        ),
    ]
