# Generated by Django 5.0.4 on 2024-05-03 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_rename_image_hotelimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='rating',
        ),
    ]
